# Generated by Django 5.1.7 on 2025-06-19 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressupostos',
            fields=[
                ('id_pressupost', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pressupost', models.CharField(blank=True, max_length=255, null=True)),
                ('data_pressupost', models.DateField(default=django.utils.timezone.now)),
                ('observacions', models.CharField(blank=True, max_length=600, null=True)),
                ('tancat', models.BooleanField(default=False)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Pressupost',
                'verbose_name_plural': 'Presuspostos',
                'db_table': 'pressupostos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PressupostosLineas',
            fields=[
                ('id_pressupost_linea', models.AutoField(primary_key=True, serialize=False)),
                ('quantitat', models.IntegerField()),
                ('preu_tancat', models.BooleanField(blank=True, null=True)),
                ('cost_tancat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('increment_hores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hores_totales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost_hores', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost_hores_totals', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('subtotal_linea', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('benefici_linea', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_linea', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Pressuost Linea',
                'verbose_name_plural': 'Pessupostos Linees',
                'db_table': 'pressupostos_lineas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PressupostPDFVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('archivo', models.FileField(upload_to='pdfs_pressupostos/')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pressupost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_versions', to='pressupostos.pressupostos')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('pressupost', 'version')},
            },
        ),
    ]
