# Generated by Django 5.1.7 on 2025-06-19 18:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nomclient', models.CharField(max_length=100, verbose_name='Nom del Client')),
                ('rsocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raó Social')),
                ('nrt', models.CharField(blank=True, max_length=100, null=True, verbose_name='NRT')),
                ('carrer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrer')),
                ('nro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('escala', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escala')),
                ('pis', models.IntegerField(blank=True, null=True, verbose_name='Pis')),
                ('porta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porta')),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telèfon')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correu electrònic')),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='DataCreacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='DataModificacio')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartamentClient',
            fields=[
                ('id_departament', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Departament Client')),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Departament Client',
                'verbose_name_plural': 'Departaments Clients',
                'db_table': 'departament_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desplacaments',
            fields=[
                ('id_desplacament', models.AutoField(primary_key=True, serialize=False)),
                ('increment_hores', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Increment Hores')),
                ('observacions', models.TextField(blank=True, null=True)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Desplaçament',
                'verbose_name_plural': 'Desplaçaments',
                'db_table': 'desplacaments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hores',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('hores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Hores',
                'db_table': 'hores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_parroquia', models.AutoField(primary_key=True, serialize=False)),
                ('parroquia', models.CharField(db_column='Parroquia', max_length=100)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='DataCreacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='DataModificacio')),
            ],
            options={
                'verbose_name': 'Parròquia',
                'verbose_name_plural': 'Parròquies',
                'db_table': 'parroquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaContactClient',
            fields=[
                ('id_persona_contact', models.AutoField(primary_key=True, serialize=False)),
                ('nom_contacte', models.CharField(max_length=100, verbose_name='Contacte Client')),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telèfon')),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Contacte Client',
                'verbose_name_plural': 'Contactes Client',
                'db_table': 'persona_contact_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poblacio',
            fields=[
                ('id_poblacio', models.AutoField(primary_key=True, serialize=False)),
                ('poblacio', models.CharField(db_column='Poblacio', max_length=100)),
                ('codipostal', models.CharField(db_column='CodiPostal', max_length=100)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='DataCreacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='DataModificacio')),
            ],
            options={
                'verbose_name': 'Població',
                'verbose_name_plural': 'Poblacions',
                'db_table': 'poblacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('preutancat', models.IntegerField(db_column='PreuTancat')),
                ('preuhora', models.DecimalField(db_column='PreuHora', decimal_places=2, max_digits=10)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='DataCreacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='DataModificacio')),
            ],
            options={
                'verbose_name': 'Recurs',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasca',
            fields=[
                ('id_tasca', models.AutoField(primary_key=True, serialize=False)),
                ('tasca', models.CharField(max_length=100)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Tasca',
                'verbose_name_plural': 'Tasques',
                'db_table': 'tasca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TasquesTreball',
            fields=[
                ('id_tasca_treball', models.AutoField(primary_key=True, serialize=False)),
                ('observacions', models.CharField(blank=True, max_length=300, null=True, verbose_name='observacions')),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Traball - Tasca',
                'verbose_name_plural': 'Treballs - Tasques',
                'db_table': 'tasques_treball',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipusrecurso',
            fields=[
                ('id_tipusrecurso', models.AutoField(primary_key=True, serialize=False)),
                ('tipus', models.CharField(max_length=100, verbose_name='Tipus Recurs')),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='DataCreacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='DataModificacio')),
            ],
            options={
                'verbose_name': 'Tipus de Recurs',
                'verbose_name_plural': 'Tipus de Recursos',
                'db_table': 'tipusrecurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treballs',
            fields=[
                ('id_treball', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.CharField(max_length=100)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Treball',
                'verbose_name_plural': 'Treballs',
                'db_table': 'treballs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacio',
            fields=[
                ('id_ubicacio', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacio', models.CharField(max_length=100, verbose_name='ubicacio')),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Ubicació',
                'verbose_name_plural': 'Ubicacions',
                'db_table': 'ubicacio',
                'managed': False,
            },
        ),
    ]
