# Generated by Django 5.1.7 on 2025-06-19 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectes',
            fields=[
                ('id_projecte', models.AutoField(primary_key=True, serialize=False)),
                ('nom_projecte', models.CharField(max_length=255)),
                ('data_peticio', models.DateField(default=django.utils.timezone.now)),
                ('observacions', models.CharField(blank=True, max_length=1200, null=True)),
                ('tancat', models.BooleanField(default=False)),
                ('datacreacio', models.DateTimeField(auto_now_add=True, db_column='data_creacio')),
                ('datamodificacio', models.DateTimeField(auto_now=True, db_column='data_modificacio')),
            ],
            options={
                'verbose_name': 'Projecte',
                'verbose_name_plural': 'Projectes',
                'db_table': 'projectes',
                'managed': False,
            },
        ),
    ]
